suffix = "subsystems.toml"

[auth]
# HTTPS
username = "your-username"
password = "your-password"

# SSH
# Not working at the moment
public_key = "private/id_rsa.pub"
private_key = "private/id_rsa"
#passphrase = "your-passphrase"

[[targets]]
url = "https://github.com/Fanaen/subsystem-mapper.git"
branch = "master"
