# System is between simple brackets: only one per file
# Also, its optional.
[system]
id = "siostam"
name = "Siostam"
description = "Create a GraphViz map of subsystems found in multiple git repositories."

    # You may display how-to links next to the system
    [[system.how_to]]
    url = "https://github.com/siostam/siostam#usage"
    text = "How-to configure Siostam"

# All subsystems below are in the system above (if there is one)
# subsystem are between double brackets: you can use as many as you want
[[subsystem]]
id = "siostam_server"
name = "Server"
description = "Serves the SVG and JSON describing the subsystems"

    # You may display how-to links next to the subsystem system
    [[subsystem.how_to]]
    url = "https://github.com/siostam/siostam#usage"
    text = "How-to run the server"
